//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("opadua08Model", "idcomentario", "comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Copa.Models.comentario), "noticia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Copa.Models.noticia), true)]
[assembly: EdmRelationshipAttribute("opadua08Model", "idusuario", "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Copa.Models.usuario), "noticia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Copa.Models.noticia), true)]
[assembly: EdmRelationshipAttribute("opadua08Model", "idtipo_usuario", "tipo_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Copa.Models.tipo_usuario), "usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Copa.Models.usuario), true)]

#endregion

namespace Copa.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GerenciarNoticiaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GerenciarNoticiaEntities object using the connection string found in the 'GerenciarNoticiaEntities' section of the application configuration file.
        /// </summary>
        public GerenciarNoticiaEntities() : base("name=GerenciarNoticiaEntities", "GerenciarNoticiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GerenciarNoticiaEntities object.
        /// </summary>
        public GerenciarNoticiaEntities(string connectionString) : base(connectionString, "GerenciarNoticiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GerenciarNoticiaEntities object.
        /// </summary>
        public GerenciarNoticiaEntities(EntityConnection connection) : base(connection, "GerenciarNoticiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comentario> comentario
        {
            get
            {
                if ((_comentario == null))
                {
                    _comentario = base.CreateObjectSet<comentario>("comentario");
                }
                return _comentario;
            }
        }
        private ObjectSet<comentario> _comentario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<noticia> noticia
        {
            get
            {
                if ((_noticia == null))
                {
                    _noticia = base.CreateObjectSet<noticia>("noticia");
                }
                return _noticia;
            }
        }
        private ObjectSet<noticia> _noticia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipo_usuario> tipo_usuario
        {
            get
            {
                if ((_tipo_usuario == null))
                {
                    _tipo_usuario = base.CreateObjectSet<tipo_usuario>("tipo_usuario");
                }
                return _tipo_usuario;
            }
        }
        private ObjectSet<tipo_usuario> _tipo_usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comentario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomentario(comentario comentario)
        {
            base.AddObject("comentario", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the noticia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonoticia(noticia noticia)
        {
            base.AddObject("noticia", noticia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipo_usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipo_usuario(tipo_usuario tipo_usuario)
        {
            base.AddObject("tipo_usuario", tipo_usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua08Model", Name="comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comentario object.
        /// </summary>
        /// <param name="idcomentario">Initial value of the idcomentario property.</param>
        /// <param name="conteudo">Initial value of the conteudo property.</param>
        /// <param name="data">Initial value of the data property.</param>
        public static comentario Createcomentario(global::System.Int32 idcomentario, global::System.String conteudo, global::System.DateTime data)
        {
            comentario comentario = new comentario();
            comentario.idcomentario = idcomentario;
            comentario.conteudo = conteudo;
            comentario.data = data;
            return comentario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcomentario
        {
            get
            {
                return _idcomentario;
            }
            set
            {
                if (_idcomentario != value)
                {
                    OnidcomentarioChanging(value);
                    ReportPropertyChanging("idcomentario");
                    _idcomentario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcomentario");
                    OnidcomentarioChanged();
                }
            }
        }
        private global::System.Int32 _idcomentario;
        partial void OnidcomentarioChanging(global::System.Int32 value);
        partial void OnidcomentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String conteudo
        {
            get
            {
                return _conteudo;
            }
            set
            {
                OnconteudoChanging(value);
                ReportPropertyChanging("conteudo");
                _conteudo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("conteudo");
                OnconteudoChanged();
            }
        }
        private global::System.String _conteudo;
        partial void OnconteudoChanging(global::System.String value);
        partial void OnconteudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idcomentario", "noticia")]
        public EntityCollection<noticia> noticia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<noticia>("opadua08Model.idcomentario", "noticia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<noticia>("opadua08Model.idcomentario", "noticia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua08Model", Name="noticia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class noticia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new noticia object.
        /// </summary>
        /// <param name="idnoticia">Initial value of the idnoticia property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        /// <param name="data">Initial value of the data property.</param>
        /// <param name="conteudo">Initial value of the conteudo property.</param>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        /// <param name="idcomentario">Initial value of the idcomentario property.</param>
        public static noticia Createnoticia(global::System.Int32 idnoticia, global::System.String titulo, global::System.DateTime data, global::System.String conteudo, global::System.Int32 idusuario, global::System.Int32 idcomentario)
        {
            noticia noticia = new noticia();
            noticia.idnoticia = idnoticia;
            noticia.titulo = titulo;
            noticia.data = data;
            noticia.conteudo = conteudo;
            noticia.idusuario = idusuario;
            noticia.idcomentario = idcomentario;
            return noticia;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idnoticia
        {
            get
            {
                return _idnoticia;
            }
            set
            {
                if (_idnoticia != value)
                {
                    OnidnoticiaChanging(value);
                    ReportPropertyChanging("idnoticia");
                    _idnoticia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idnoticia");
                    OnidnoticiaChanged();
                }
            }
        }
        private global::System.Int32 _idnoticia;
        partial void OnidnoticiaChanging(global::System.Int32 value);
        partial void OnidnoticiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String conteudo
        {
            get
            {
                return _conteudo;
            }
            set
            {
                OnconteudoChanging(value);
                ReportPropertyChanging("conteudo");
                _conteudo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("conteudo");
                OnconteudoChanged();
            }
        }
        private global::System.String _conteudo;
        partial void OnconteudoChanging(global::System.String value);
        partial void OnconteudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                OnidusuarioChanging(value);
                ReportPropertyChanging("idusuario");
                _idusuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idusuario");
                OnidusuarioChanged();
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcomentario
        {
            get
            {
                return _idcomentario;
            }
            set
            {
                OnidcomentarioChanging(value);
                ReportPropertyChanging("idcomentario");
                _idcomentario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcomentario");
                OnidcomentarioChanged();
            }
        }
        private global::System.Int32 _idcomentario;
        partial void OnidcomentarioChanging(global::System.Int32 value);
        partial void OnidcomentarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idcomentario", "comentario")]
        public comentario comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comentario>("opadua08Model.idcomentario", "comentario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comentario>("opadua08Model.idcomentario", "comentario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<comentario> comentarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comentario>("opadua08Model.idcomentario", "comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<comentario>("opadua08Model.idcomentario", "comentario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idusuario", "usuario")]
        public usuario usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("opadua08Model.idusuario", "usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("opadua08Model.idusuario", "usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuario> usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuario>("opadua08Model.idusuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuario>("opadua08Model.idusuario", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua08Model", Name="tipo_usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipo_usuario object.
        /// </summary>
        /// <param name="idtipo_usuario">Initial value of the idtipo_usuario property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        public static tipo_usuario Createtipo_usuario(global::System.Int32 idtipo_usuario, global::System.String tipo)
        {
            tipo_usuario tipo_usuario = new tipo_usuario();
            tipo_usuario.idtipo_usuario = idtipo_usuario;
            tipo_usuario.tipo = tipo;
            return tipo_usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtipo_usuario
        {
            get
            {
                return _idtipo_usuario;
            }
            set
            {
                if (_idtipo_usuario != value)
                {
                    Onidtipo_usuarioChanging(value);
                    ReportPropertyChanging("idtipo_usuario");
                    _idtipo_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idtipo_usuario");
                    Onidtipo_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _idtipo_usuario;
        partial void Onidtipo_usuarioChanging(global::System.Int32 value);
        partial void Onidtipo_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idtipo_usuario", "usuario")]
        public EntityCollection<usuario> usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuario>("opadua08Model.idtipo_usuario", "usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuario>("opadua08Model.idtipo_usuario", "usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua08Model", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="idtipo_usuario">Initial value of the idtipo_usuario property.</param>
        public static usuario Createusuario(global::System.Int32 idusuario, global::System.String nome, global::System.String senha, global::System.String email, global::System.Int32 idtipo_usuario)
        {
            usuario usuario = new usuario();
            usuario.idusuario = idusuario;
            usuario.nome = nome;
            usuario.senha = senha;
            usuario.email = email;
            usuario.idtipo_usuario = idtipo_usuario;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idtipo_usuario
        {
            get
            {
                return _idtipo_usuario;
            }
            set
            {
                Onidtipo_usuarioChanging(value);
                ReportPropertyChanging("idtipo_usuario");
                _idtipo_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idtipo_usuario");
                Onidtipo_usuarioChanged();
            }
        }
        private global::System.Int32 _idtipo_usuario;
        partial void Onidtipo_usuarioChanging(global::System.Int32 value);
        partial void Onidtipo_usuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idusuario", "noticia")]
        public EntityCollection<noticia> noticia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<noticia>("opadua08Model.idusuario", "noticia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<noticia>("opadua08Model.idusuario", "noticia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua08Model", "idtipo_usuario", "tipo_usuario")]
        public tipo_usuario tipo_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_usuario>("opadua08Model.idtipo_usuario", "tipo_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_usuario>("opadua08Model.idtipo_usuario", "tipo_usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipo_usuario> tipo_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_usuario>("opadua08Model.idtipo_usuario", "tipo_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipo_usuario>("opadua08Model.idtipo_usuario", "tipo_usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
