//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("opadua05Model", "iduser", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Copa.Models.user), "post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Copa.Models.post), true)]

#endregion

namespace Copa.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class teste01Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new teste01Entities object using the connection string found in the 'teste01Entities' section of the application configuration file.
        /// </summary>
        public teste01Entities() : base("name=teste01Entities", "teste01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new teste01Entities object.
        /// </summary>
        public teste01Entities(string connectionString) : base(connectionString, "teste01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new teste01Entities object.
        /// </summary>
        public teste01Entities(EntityConnection connection) : base(connection, "teste01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<post> post
        {
            get
            {
                if ((_post == null))
                {
                    _post = base.CreateObjectSet<post>("post");
                }
                return _post;
            }
        }
        private ObjectSet<post> _post;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the post EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopost(post post)
        {
            base.AddObject("post", post);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua05Model", Name="post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new post object.
        /// </summary>
        /// <param name="idpost">Initial value of the idpost property.</param>
        /// <param name="iduser">Initial value of the iduser property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        /// <param name="post1">Initial value of the post1 property.</param>
        /// <param name="data">Initial value of the data property.</param>
        public static post Createpost(global::System.Int32 idpost, global::System.Int32 iduser, global::System.String titulo, global::System.String post1, global::System.DateTime data)
        {
            post post = new post();
            post.idpost = idpost;
            post.iduser = iduser;
            post.titulo = titulo;
            post.post1 = post1;
            post.data = data;
            return post;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idpost
        {
            get
            {
                return _idpost;
            }
            set
            {
                if (_idpost != value)
                {
                    OnidpostChanging(value);
                    ReportPropertyChanging("idpost");
                    _idpost = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idpost");
                    OnidpostChanged();
                }
            }
        }
        private global::System.Int32 _idpost;
        partial void OnidpostChanging(global::System.Int32 value);
        partial void OnidpostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iduser
        {
            get
            {
                return _iduser;
            }
            set
            {
                OniduserChanging(value);
                ReportPropertyChanging("iduser");
                _iduser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iduser");
                OniduserChanged();
            }
        }
        private global::System.Int32 _iduser;
        partial void OniduserChanging(global::System.Int32 value);
        partial void OniduserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String post1
        {
            get
            {
                return _post1;
            }
            set
            {
                Onpost1Changing(value);
                ReportPropertyChanging("post1");
                _post1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("post1");
                Onpost1Changed();
            }
        }
        private global::System.String _post1;
        partial void Onpost1Changing(global::System.String value);
        partial void Onpost1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua05Model", "iduser", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("opadua05Model.iduser", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("opadua05Model.iduser", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("opadua05Model.iduser", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("opadua05Model.iduser", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="opadua05Model", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="iduser">Initial value of the iduser property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        public static user Createuser(global::System.Int32 iduser, global::System.String name, global::System.String senha)
        {
            user user = new user();
            user.iduser = iduser;
            user.name = name;
            user.senha = senha;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iduser
        {
            get
            {
                return _iduser;
            }
            set
            {
                if (_iduser != value)
                {
                    OniduserChanging(value);
                    ReportPropertyChanging("iduser");
                    _iduser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iduser");
                    OniduserChanged();
                }
            }
        }
        private global::System.Int32 _iduser;
        partial void OniduserChanging(global::System.Int32 value);
        partial void OniduserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("opadua05Model", "iduser", "post")]
        public EntityCollection<post> post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<post>("opadua05Model.iduser", "post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<post>("opadua05Model.iduser", "post", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
